language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jbevans451212/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbevans451212/docker-react npm run test